=== crithead/xercesc/dictionary.dtd
<!DOCTYPE dictionary
[
<!ELEMENT dictionary (value+)>
<!ELEMENT value (#CDATA)>
<!ATTLIST dictionary name CDATA "dictionary">
<!ATTLIST value key CDATA #REQUIRED>
]>

=== crithead/xercesc/dictwithdtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">
<dictionary name="Fruit colors">
	<value key="Apple">red,green</value>
	<value key="Banana">yellow</value>
	<value key="Cherry">red</value>
	<value key="Date">brown</value>
	<value key="Elderberry">various</value>
	<value key="Fig">green,brown</value>
	<value key="Orange">orange</value>
</dictionary>
